swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Blockchain api feature'
  description: 'Api Rest that exposes the services of the BlockChain network to be consumed internally.'
paths: 
  /payments/{paymentID}:
    post:
      summary: Registrar una pago en Blockchain
      description: Registrar una pago en Blockchain
      parameters: 
        - name: paymentID
          in: path
          required: true
          type: string
        - name: Payment
          in: body
          required: true
          schema:
            $ref: '#/definitions/PaymentRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PaymentResponse'
  
  /transactions/{transactionHash}:
    get:
      summary: Obtener los datos de la transaccion registrados en la blockchain.
      description: Obtener los datos de la transaccion registrados en la blockchain.
      parameters: 
        - name: transactionHash
          in: path
          required: true
          type: string
          minLength: 60
          maxLength: 70
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TransactionResponse'
    
          
definitions:

  TransactionResponse:
    type: object
    properties:
      eventID:
        type: integer
        format: int64
      beneficiary:
        type: integer
        format: int64
      amount:
        type: integer
        format: int64

  PaymentRequest:
    type: object
    properties:
      eventID:
        type: integer
        format: int64
      beneficiary:
        type: integer
        format: int64
      amount:
        type: integer
        format: int64
  
  PaymentResponse:
    type: object
    properties:
      transactionHash:
        type: string
      blocknumber:
        type: integer
        format: int64
      timestamp:
        type: integer
        format: int64
    
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /pedrodlf/LiberBank-BlockChain/1.0.0
schemes:
 - https